class LawItem {
  final String id;
  final String title;
  final String category;
  final String description;
  final String fullText;
  final String section;
  final String punishment;
  final List<String> keyPoints;

  const LawItem({
    required this.id,
    required this.title,
    required this.category,
    required this.description,
    required this.fullText,
    required this.section,
    required this.punishment,
    required this.keyPoints,
  });
}

class LawsData {
  static final List<LawItem> allLaws = [
    LawItem(
      id: '1',
      title: 'Protection Against Assault & Molestation',
      category: 'Women Safety',
      section: 'Section 354 IPC',
      description: 'Assault or criminal force to woman with intent to outrage her modesty',
      fullText: 'Whoever assaults or uses criminal force to any woman, intending to outrage or knowing it to be likely that he will thereby outrage her modesty, shall be punished with imprisonment of either description for a term which shall not be less than one year but which may extend to five years, and shall also be liable to fine.',
      punishment: 'Imprisonment: 1-5 years + Fine',
      keyPoints: [
        'Covers any unwanted physical contact',
        'Includes eve-teasing and molestation',
        'Non-bailable offense',
        'Woman\'s statement is strong evidence',
        'Can file FIR at any police station',
      ],
    ),
    LawItem(
      id: '2',
      title: 'Sexual Harassment at Workplace',
      category: 'Workplace Rights',
      section: 'POSH Act 2013',
      description: 'Prevention of Sexual Harassment at Workplace Act',
      fullText: 'Sexual harassment includes unwelcome sexually determined behavior (whether directly or by implication) such as: physical contact and advances, demand or request for sexual favors, sexually colored remarks, showing pornography, any other unwelcome physical, verbal or non-verbal conduct of sexual nature.',
      punishment: 'Service rules action + Compensation + Criminal prosecution',
      keyPoints: [
        'Every workplace must have Internal Committee',
        'Can file complaint within 3 months',
        'Inquiry must complete in 90 days',
        'Employer liable if no action taken',
        'Complainant identity protected',
      ],
    ),
    LawItem(
      id: '3',
      title: 'Domestic Violence Protection',
      category: 'Family Law',
      section: 'DV Act 2005',
      description: 'Protection of Women from Domestic Violence',
      fullText: 'Any act, omission or commission or conduct of the respondent shall constitute domestic violence if it harms or injures or endangers the health, safety, life, limb or well-being, whether mental or physical, of the aggrieved person or tends to do so and includes causing physical abuse, sexual abuse, verbal and emotional abuse and economic abuse.',
      punishment: 'Protection orders, Residence orders, Monetary relief, Custody orders',
      keyPoints: [
        'Covers physical, sexual, verbal, emotional & economic abuse',
        'Protection to women in live-in relationships',
        'Right to reside in shared household',
        'Can claim maintenance and compensation',
        'Protection Officers assist victims',
      ],
    ),
    LawItem(
      id: '4',
      title: 'Dowry Harassment Protection',
      category: 'Family Law',
      section: 'Section 498A IPC',
      description: 'Husband or relative of husband subjecting woman to cruelty',
      fullText: 'Whoever, being the husband or the relative of the husband of a woman, subjects such woman to cruelty shall be punished with imprisonment for a term which may extend to three years and shall also be liable to fine. Explanation: Cruelty means any willful conduct which is of such a nature as is likely to drive the woman to commit suicide or to cause grave injury or danger to life, limb or health of the woman; or harassment of the woman with a view to coercing her or any person related to her to meet any unlawful demand for any property or valuable security.',
      punishment: 'Imprisonment up to 3 years + Fine',
      keyPoints: [
        'Non-bailable and cognizable offense',
        'Covers harassment for dowry',
        'Husband and in-laws can be arrested',
        'Police must register FIR immediately',
        'Woman can claim maintenance',
      ],
    ),
    LawItem(
      id: '5',
      title: 'Stalking Protection',
      category: 'Women Safety',
      section: 'Section 354D IPC',
      description: 'Stalking - Following or monitoring a woman',
      fullText: 'Any man who follows a woman and contacts, or attempts to contact such woman to foster personal interaction repeatedly despite a clear indication of disinterest; or monitors the use by a woman of the internet, email or any other form of electronic communication commits the offense of stalking.',
      punishment: 'First offense: up to 3 years + Fine. Subsequent: up to 5 years + Fine',
      keyPoints: [
        'Includes physical and cyber stalking',
        'Clear "no" is sufficient evidence',
        'Monitoring social media is stalking',
        'Take screenshots as evidence',
        'Report to Cyber Cell for online stalking',
      ],
    ),
    LawItem(
      id: '6',
      title: 'Voyeurism Protection',
      category: 'Women Safety',
      section: 'Section 354C IPC',
      description: 'Watching or capturing images of woman in private act',
      fullText: 'Any man who watches, or captures the image of a woman engaging in a private act in circumstances where she would usually have the expectation of not being observed either by the perpetrator or by any other person at the behest of the perpetrator or disseminates such image shall be punished.',
      punishment: 'First offense: 1-3 years + Fine. Subsequent: 3-7 years + Fine',
      keyPoints: [
        'Covers hidden cameras and recording',
        'Sharing such images is also punishable',
        'Private act includes changing clothes, bathing',
        'Non-bailable for repeat offenders',
        'Devices can be seized as evidence',
      ],
    ),
    LawItem(
      id: '7',
      title: 'Cyber Harassment Protection',
      category: 'Cyber Crimes',
      section: 'IT Act Sec 66A, 67',
      description: 'Sending offensive messages and publishing obscene content',
      fullText: 'Section 66E: Violation of privacy - Punishment with imprisonment up to 3 years or fine up to 2 lakh rupees. Section 67: Publishing obscene content - Punishment with imprisonment up to 3 years and fine up to 5 lakh rupees. Section 67A: Publishing sexually explicit content - Punishment up to 5 years and fine up to 10 lakh rupees.',
      punishment: 'Imprisonment: 3-5 years + Fine up to 10 lakh',
      keyPoints: [
        'Covers morphed images and fake profiles',
        'Revenge porn is punishable',
        'Report to www.cybercrime.gov.in',
        'Save all evidence (screenshots, URLs)',
        'Complaint can be filed online',
      ],
    ),
    LawItem(
      id: '8',
      title: 'Verbal & Gestural Harassment',
      category: 'Women Safety',
      section: 'Section 509 IPC',
      description: 'Word, gesture or act intended to insult modesty of a woman',
      fullText: 'Whoever, intending to insult the modesty of any woman, utters any word, makes any sound or gesture, or exhibits any object, intending that such word or sound shall be heard, or that such gesture or object shall be seen, by such woman, or intrudes upon the privacy of such woman, shall be punished with simple imprisonment for a term which may extend to three years, and also with fine.',
      punishment: 'Imprisonment up to 3 years + Fine',
      keyPoints: [
        'Covers eve-teasing and catcalling',
        'Lewd gestures or comments punishable',
        'Can report immediately to police',
        'Bystanders can be witnesses',
        'Dial 100 or 1091 for immediate help',
      ],
    ),
    LawItem(
      id: '9',
      title: 'Right to Information (RTI)',
      category: 'Legal Rights',
      section: 'RTI Act 2005',
      description: 'Right to seek information from public authorities',
      fullText: 'Every citizen has the right to information from public authorities. This includes the right to inspect documents, take notes, obtain certified copies of documents or records, and obtain information in the form of diskettes, floppies, tapes, video cassettes or in any other electronic mode.',
      punishment: 'Not applicable - This is a right, not an offense',
      keyPoints: [
        'Can request any government information',
        'Application fee: ₹10 only',
        'Response within 30 days mandatory',
        'Use to check police investigation status',
        'Free for Below Poverty Line citizens',
      ],
    ),
    LawItem(
      id: '10',
      title: 'Right Against Wrongful Confinement',
      category: 'Legal Rights',
      section: 'Section 340-348 IPC',
      description: 'Protection against illegal detention',
      fullText: 'Whoever wrongfully restrains any person in such a manner as to prevent that person from proceeding beyond certain circumscribing limits, is said to wrongfully confine that person. Wrongful confinement is punishable with imprisonment up to one year or fine up to ₹1000 or both.',
      punishment: 'Imprisonment up to 1-3 years + Fine',
      keyPoints: [
        'Cannot be detained without legal reason',
        'Locking someone in room is confinement',
        'Can file Habeas Corpus petition',
        'Police must inform family of arrest',
        'Woman can only be arrested by female officer',
      ],
    ),
    LawItem(
      id: '11',
      title: 'Consumer Protection Rights',
      category: 'Fraud Prevention',
      section: 'Consumer Protection Act 2019',
      description: 'Protection against fraud and defective products/services',
      fullText: 'Rights of consumers include: Right to be protected against marketing of goods and services which are hazardous; Right to be informed about quality, quantity, potency, purity, standard and price; Right to be assured access to variety of goods and services at competitive prices; Right to be heard and seek redressal.',
      punishment: 'Compensation + Penalty on seller/service provider',
      keyPoints: [
        'Can file complaint for defective products',
        'E-commerce purchases also covered',
        'Online complaint filing available',
        'No court fee for complaints up to ₹5 lakh',
        'Dispute resolution within 90 days',
      ],
    ),
    LawItem(
      id: '12',
      title: 'Fraud & Cheating Protection',
      category: 'Fraud Prevention',
      section: 'Section 420 IPC',
      description: 'Cheating and dishonestly inducing delivery of property',
      fullText: 'Whoever cheats and thereby dishonestly induces the person deceived to deliver any property to any person, or to make, alter or destroy the whole or any part of a valuable security, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.',
      punishment: 'Imprisonment up to 7 years + Fine',
      keyPoints: [
        'Covers financial fraud and scams',
        'Online fraud also punishable',
        'Report to Economic Offences Wing',
        'Keep all transaction receipts',
        'Can track through Cyber Crime portal',
      ],
    ),
    LawItem(
      id: '13',
      title: 'Equal Remuneration Act',
      category: 'Workplace Rights',
      section: 'ERA 1976',
      description: 'Equal pay for equal work for men and women',
      fullText: 'No employer shall pay to any worker, employed by him in an establishment, remuneration at rates less favourable than those at which remuneration is paid by him to the workers of the opposite sex in such establishment for performing the same work or work of a similar nature.',
      punishment: 'Fine up to ₹10,000 for first offense, ₹20,000 + imprisonment for subsequent',
      keyPoints: [
        'Same pay for same work regardless of gender',
        'Applies to all establishments',
        'Can file complaint with Labour Commissioner',
        'Employer cannot discriminate in recruitment',
        'Covers salary, allowances, and benefits',
      ],
    ),
    LawItem(
      id: '14',
      title: 'Maternity Benefit Rights',
      category: 'Workplace Rights',
      section: 'Maternity Benefit Act 1961',
      description: 'Protection and benefits for working mothers',
      fullText: 'Every woman shall be entitled to maternity benefit at the rate of the average daily wage for the period of her actual absence, that is to say, the period immediately preceding the day of her delivery, the actual day of her delivery and any period immediately following that day.',
      punishment: 'Fine + Compensation to employee',
      keyPoints: [
        '26 weeks paid maternity leave (6 months)',
        'Cannot be dismissed during pregnancy',
        'Work from home option for nursing mothers',
        'Crèche facility mandatory in large companies',
        'Medical bonus of ₹3,500 if no prenatal care',
      ],
    ),
    LawItem(
      id: '15',
      title: 'Right to Education',
      category: 'Legal Rights',
      section: 'RTE Act 2009',
      description: 'Free and compulsory education for children',
      fullText: 'Every child of the age of six to fourteen years shall have a right to free and compulsory elementary education in a neighbourhood school till completion of elementary education.',
      punishment: 'Fine on schools/authorities denying admission',
      keyPoints: [
        'Free education for children 6-14 years',
        'No capitation fees allowed',
        '25% seats reserved for economically weaker sections',
        'No child can be held back till Class 8',
        'Government must provide school within 1 km',
      ],
    ),
    LawItem(
      id: '16',
      title: 'Minimum Wages Act',
      category: 'Workplace Rights',
      section: 'Minimum Wages Act 1948',
      description: 'Ensures minimum wages for workers',
      fullText: 'The appropriate Government shall fix the minimum rates of wages payable to employees employed in an employment specified in Part I or Part II of the Schedule and review such minimum rates of wages at intervals not exceeding five years.',
      punishment: 'Imprisonment up to 6 months + Fine up to ₹20,000',
      keyPoints: [
        'Employer must pay at least minimum wage',
        'Varies by state and occupation',
        'Includes basic + allowances',
        'Cannot force to work without minimum wage',
        'File complaint with Labour Inspector',
      ],
    ),
    LawItem(
      id: '17',
      title: 'Medical Termination of Pregnancy',
      category: 'Women Safety',
      section: 'MTP Act 1971 (Amended 2021)',
      description: 'Legal abortion rights for women',
      fullText: 'A pregnancy may be terminated by a registered medical practitioner if the length of the pregnancy does not exceed twenty weeks, or where the pregnancy is between twenty to twenty-four weeks with the opinion of two registered medical practitioners, if they are of opinion, formed in good faith, that the continuance of the pregnancy would involve a risk to the life of the pregnant woman or of grave injury to her physical or mental health.',
      punishment: 'Punishment for illegal abortion providers',
      keyPoints: [
        'Legal abortion up to 24 weeks (earlier 20)',
        'Woman\'s consent is sufficient',
        'Privacy protected - name not disclosed',
        'Safe and legal in registered facilities',
        'No permission from husband/partner needed',
      ],
    ),
    LawItem(
      id: '18',
      title: 'Indecent Representation of Women',
      category: 'Women Safety',
      section: 'IRWA Act 1986',
      description: 'Prohibition of indecent representation',
      fullText: 'No person shall produce or cause to be produced, sell, let to hire, distribute, circulate or send by post any book, pamphlet, paper, slide, film, writing, drawing, painting, photograph, representation or figure which contains indecent representation of women in any form.',
      punishment: 'First offense: 2 years + Fine up to ₹2,000. Second: 6 months to 5 years + Fine',
      keyPoints: [
        'Covers objectification in media and ads',
        'Includes digital/online content',
        'Can file complaint with police/authorities',
        'Indecent = derogatory to women',
        'Protects dignity and respect',
      ],
    ),
    LawItem(
      id: '19',
      title: 'Right Against Forced Marriage',
      category: 'Family Law',
      section: 'Section 366 IPC',
      description: 'Kidnapping or abduction to compel marriage',
      fullText: 'Whoever kidnaps or abducts any woman with intent that she may be compelled, or knowing it to be likely that she will be compelled, to marry any person against her will, or in order that she may be forced or seduced to illicit intercourse, shall be punished with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.',
      punishment: 'Imprisonment up to 10 years + Fine',
      keyPoints: [
        'Marriage requires free consent',
        'Forced marriage is illegal',
        'Minimum age: 21 for men, 18 for women',
        'Can file FIR immediately',
        'Marriage can be declared void',
      ],
    ),
    LawItem(
      id: '20',
      title: 'Prohibition of Child Marriage',
      category: 'Family Law',
      section: 'PCMA 2006',
      description: 'Prevention of child marriage',
      fullText: 'A child marriage is voidable at the option of the contracting party who was a child at the time of the marriage. A petition for annulling a child marriage may be filed in the district court by a contracting party to the marriage who was a child at the time of the marriage.',
      punishment: 'Imprisonment up to 2 years + Fine up to ₹1 lakh',
      keyPoints: [
        'Illegal to marry before 18 (girls) or 21 (boys)',
        'Marriage can be annulled within 2 years',
        'Punishment for parents/guardians performing',
        'Child Marriage Prohibition Officers appointed',
        'Report on 1098 Child Helpline',
      ],
    ),
    LawItem(
      id: '21',
      title: 'Protection from Acid Attack',
      category: 'Women Safety',
      section: 'Section 326A IPC',
      description: 'Punishment for acid attack',
      fullText: 'Whoever causes permanent or partial damage or deformity to, or burns or maims or disfigures or disables, any part of the body of a person or causes grievous hurt by throwing acid on or by administering acid to that person, shall be punished with imprisonment of either description for a term which shall not be less than ten years but which may extend to imprisonment for life, and with fine.',
      punishment: 'Minimum 10 years to life imprisonment + Fine (for victim compensation)',
      keyPoints: [
        'Minimum 10 years imprisonment',
        'Victim entitled to compensation',
        'Free medical treatment by government',
        'Sale of acid regulated - need ID proof',
        'Attempt is also punishable',
      ],
    ),
    LawItem(
      id: '22',
      title: 'Employment Injury Benefits',
      category: 'Workplace Rights',
      section: 'ESI Act 1948',
      description: 'Social security for employees',
      fullText: 'The Act provides for medical, sickness, maternity, disablement and dependent benefits in the contingency of death or disablement of insured persons covered under the scheme due to employment injury or occupational hazards.',
      punishment: 'Penalty for non-compliance by employer',
      keyPoints: [
        'Free medical treatment for work injuries',
        'Cash benefits during sickness',
        'Maternity benefits for 26 weeks',
        'Disability and death benefits',
        'Applies to establishments with 10+ employees',
      ],
    ),
    LawItem(
      id: '23',
      title: 'Payment of Gratuity',
      category: 'Workplace Rights',
      section: 'Gratuity Act 1972',
      description: 'Retirement benefit for employees',
      fullText: 'Gratuity shall be payable to an employee on the termination of his employment after he has rendered continuous service for not less than five years on his superannuation, or on his retirement or resignation, or on his death or disablement.',
      punishment: 'Imprisonment up to 2 years for non-payment',
      keyPoints: [
        'Payable after 5 years of service',
        'Formula: Last drawn salary × 15/26 × years worked',
        'Tax free up to ₹20 lakh',
        'Must be paid within 30 days',
        'Can claim even after resignation',
      ],
    ),
    LawItem(
      id: '24',
      title: 'Data Privacy Rights',
      category: 'Cyber Crimes',
      section: 'IT Act Section 43A, 72A',
      description: 'Protection of personal data',
      fullText: 'Where a body corporate, possessing, dealing or handling any sensitive personal data or information in a computer resource which it owns, controls or operates, is negligent in implementing and maintaining reasonable security practices and procedures and thereby causes wrongful loss or wrongful gain to any person, such body corporate shall be liable to pay damages by way of compensation.',
      punishment: 'Compensation to affected person + Imprisonment up to 3 years',
      keyPoints: [
        'Companies must protect your data',
        'Consent required for data collection',
        'Right to know what data is stored',
        'Can demand data deletion',
        'Report data breaches to CERT-In',
      ],
    ),
    LawItem(
      id: '25',
      title: 'Prevention of Money Laundering',
      category: 'Fraud Prevention',
      section: 'PMLA 2002',
      description: 'Anti-money laundering law',
      fullText: 'Whosoever directly or indirectly attempts to indulge or knowingly assists or knowingly is a party or is actually involved in any process or activity connected with the proceeds of crime including its concealment, possession, acquisition or use and projecting or claiming it as untainted property shall be guilty of offence of money-laundering.',
      punishment: 'Rigorous imprisonment: 3-7 years + Fine',
      keyPoints: [
        'PAN and Aadhaar mandatory for transactions',
        'Cash transactions above ₹2 lakh reportable',
        'Banks verify source of large deposits',
        'Property can be attached/seized',
        'Report suspicious activities to FIU',
      ],
    ),
    LawItem(
      id: '26',
      title: 'Whistleblower Protection',
      category: 'Legal Rights',
      section: 'Whistleblowers Act 2014',
      description: 'Protection for those exposing corruption',
      fullText: 'Any public servant or any other person including a non-governmental organization may make a public interest disclosure before the Competent Authority related to an act of corruption, willful misuse of power or discretion, criminal offence by a public servant.',
      punishment: 'Protection from harassment, penalty on those threatening whistleblowers',
      keyPoints: [
        'Identity protected by authorities',
        'Cannot be punished for disclosure',
        'Protection from harassment/dismissal',
        'Complaint to Central/State Vigilance',
        'False complaints punishable',
      ],
    ),
    LawItem(
      id: '27',
      title: 'Prohibition of Forced Begging',
      category: 'Legal Rights',
      section: 'Various State Acts',
      description: 'Prevention of forced begging',
      fullText: 'Several states have laws prohibiting forced begging and providing rehabilitation. The Immoral Traffic (Prevention) Act also covers trafficking for begging. Anyone forcing another person, especially children, into begging can be prosecuted.',
      punishment: 'Imprisonment 3-10 years for forcing others to beg',
      keyPoints: [
        'Forced begging is a crime',
        'Children cannot be used for begging',
        'Rescue and rehabilitation provided',
        'Call 1098 for child beggars',
        'Anti-trafficking cells in every state',
      ],
    ),
    LawItem(
      id: '28',
      title: 'Driving Without License',
      category: 'Traffic Rules',
      section: 'Section 181 MV Act',
      description: 'Driving without valid driving license',
      fullText: 'Whoever drives a motor vehicle in any public place without holding an effective driving licence issued to him authorising him to drive the vehicle shall be punishable for the first offence with a fine which may extend to five thousand rupees, and for any second or subsequent offence with imprisonment which may extend to one year or with fine which may extend to ten thousand rupees or with both.',
      punishment: 'First offense: Fine up to ₹5,000 | Repeat: 1 year imprisonment or ₹10,000 fine',
      keyPoints: [
        'Valid license mandatory for driving',
        'Learner must have qualified instructor',
        'Different license for different vehicles',
        'License must be carried while driving',
        'International license for foreign nationals',
      ],
    ),
    LawItem(
      id: '29',
      title: 'Over Speeding',
      category: 'Traffic Rules',
      section: 'Section 183 MV Act',
      description: 'Excessive speed and dangerous driving',
      fullText: 'Whoever drives a motor vehicle at a speed or in a manner which is dangerous to the public, having regard to all the circumstances shall be liable for the first offence to imprisonment up to 6 months or fine up to ₹1,000 or both, and for subsequent offence to imprisonment up to 2 years or fine up to ₹2,000 or both.',
      punishment: 'First: 6 months + ₹1,000 | Repeat: 2 years + ₹2,000',
      keyPoints: [
        'Speed limits: 50 km/h in cities, 80 km/h highways',
        'School zones: 25 km/h',
        'Heavy vehicles have lower limits',
        'Speed cameras monitor automatically',
        'License can be suspended for repeat violations',
      ],
    ),
    LawItem(
      id: '30',
      title: 'Drunk Driving',
      category: 'Traffic Rules',
      section: 'Section 185 MV Act',
      description: 'Driving under influence of alcohol or drugs',
      fullText: 'Whoever, while driving a motor vehicle, has alcohol in his blood exceeding 30 mg per 100 ml of blood detected in his breath, blood or urine, shall be punishable for the first offence with imprisonment for a term which may extend to six months, or with fine up to ₹10,000, or with both; and for a second or subsequent offence with imprisonment for a term which may extend to two years, or with fine up to ₹15,000, or with both.',
      punishment: 'First: 6 months + ₹10,000 | Repeat: 2 years + ₹15,000',
      keyPoints: [
        'Legal limit: 30mg alcohol per 100ml blood',
        'Breathalyzer test mandatory if suspected',
        'Refusing test is also punishable',
        'License suspended immediately',
        'Vehicle may be impounded',
      ],
    ),
    LawItem(
      id: '31',
      title: 'No Helmet / Seat Belt',
      category: 'Traffic Rules',
      section: 'Section 129 & 194B MV Act',
      description: 'Mandatory safety equipment violations',
      fullText: 'Every person driving a two-wheeler shall wear protective headgear. Every person occupying the front seat of a motor vehicle shall wear a seat belt while the vehicle is in motion. Violation is punishable with fine of ₹1,000 and/or disqualification of license for 3 months.',
      punishment: 'Fine ₹1,000 + License suspension up to 3 months',
      keyPoints: [
        'ISI marked helmet mandatory for riders & pillion',
        'Seat belt for all occupants in 4-wheelers',
        'Children under 12 not allowed in front seat',
        'Helmet must have chin strap fastened',
        'Repeat violations: higher penalty',
      ],
    ),
    LawItem(
      id: '32',
      title: 'Using Mobile While Driving',
      category: 'Traffic Rules',
      section: 'Section 184 MV Act',
      description: 'Dangerous driving including mobile phone use',
      fullText: 'Using mobile phone while driving constitutes dangerous driving and distraction. First offense punishable with fine up to ₹5,000. For subsequent offense, fine up to ₹10,000 and/or license suspension.',
      punishment: 'First: ₹5,000 | Repeat: ₹10,000 + License suspension',
      keyPoints: [
        'No handheld phone use while driving',
        'Hands-free Bluetooth allowed',
        'Texting/messaging strictly prohibited',
        'Clicking photos/videos not allowed',
        'Pull over safely to use phone',
      ],
    ),
    LawItem(
      id: '33',
      title: 'Traffic Signal Violation',
      category: 'Traffic Rules',
      section: 'Section 177 MV Act',
      description: 'Jumping red light and signal violations',
      fullText: 'Whoever violates traffic signals or directions given by police officer or disobeys road signs shall be liable to pay fine of ₹5,000 for first offense. Repeat violations may lead to license suspension and higher penalties.',
      punishment: 'Fine ₹5,000 + License points',
      keyPoints: [
        'Red light means complete stop',
        'Yellow light: prepare to stop',
        'Follow police hand signals',
        'CCTV cameras monitor violations',
        'Emergency vehicles have right of way',
      ],
    ),
    LawItem(
      id: '34',
      title: 'No Vehicle Insurance',
      category: 'Traffic Rules',
      section: 'Section 196 MV Act',
      description: 'Driving without valid insurance',
      fullText: 'Whoever drives a motor vehicle without a valid insurance policy shall be punishable with imprisonment which may extend to three months, or with fine up to ₹2,000, or with both. For subsequent offense, fine may extend to ₹4,000 and/or imprisonment.',
      punishment: 'First: 3 months + ₹2,000 | Repeat: ₹4,000 + imprisonment',
      keyPoints: [
        'Third-party insurance is mandatory',
        'Comprehensive insurance recommended',
        'Insurance copy must be in vehicle',
        'Check validity before driving',
        'Online insurance verification available',
      ],
    ),
    LawItem(
      id: '35',
      title: 'Vehicle Document Requirements',
      category: 'Traffic Rules',
      section: 'Section 177 MV Act',
      description: 'Mandatory documents to carry while driving',
      fullText: 'Driver must carry and produce on demand: Valid driving license, Vehicle registration certificate (RC), Insurance certificate, Pollution Under Control (PUC) certificate, Permit (for commercial vehicles), Fitness certificate (for old vehicles). Failure to produce attracts fine of ₹500-₹5,000.',
      punishment: 'Fine ₹500 to ₹5,000 depending on document',
      keyPoints: [
        'Carry original or DigiLocker documents',
        'DL: Driving License with photo',
        'RC: Registration Certificate',
        'Insurance valid policy copy',
        'PUC valid for 6 months (petrol), 3 months (diesel)',
      ],
    ),
    LawItem(
      id: '36',
      title: 'Overloading & Overcrowding',
      category: 'Traffic Rules',
      section: 'Section 194 MV Act',
      description: 'Carrying excess passengers or goods',
      fullText: 'No person shall drive or allow to be driven in any public place a motor vehicle which carries more than the permitted number of persons or excess load beyond the registered capacity. Violation is punishable with fine of ₹20,000 for overloading goods and ₹1,000 per extra passenger.',
      punishment: 'Goods: ₹20,000 | Passengers: ₹1,000 per extra person',
      keyPoints: [
        'Check RC for seating capacity',
        'Goods vehicles: weight limit specified',
        'Two-wheelers: only 2 persons allowed',
        'Children also count as passengers',
        'Vehicle can be seized for violations',
      ],
    ),
    LawItem(
      id: '37',
      title: 'Wrong Side Driving',
      category: 'Traffic Rules',
      section: 'Section 184 MV Act',
      description: 'Driving on wrong side of road',
      fullText: 'Driving on the wrong side of the road is considered dangerous driving. Punishable with fine up to ₹10,000 and/or imprisonment up to 6 months for first offense. License may be suspended.',
      punishment: 'Fine ₹10,000 + 6 months imprisonment + License suspension',
      keyPoints: [
        'Always drive on left side in India',
        'Overtaking only from right side',
        'One-way violations heavily penalized',
        'Major cause of head-on collisions',
        'Emergency vehicles exempted',
      ],
    ),
    LawItem(
      id: '38',
      title: 'Hit and Run',
      category: 'Traffic Rules',
      section: 'Section 161 & 279 IPC',
      description: 'Leaving accident scene without helping',
      fullText: 'Whoever causes death or grievous injury by rash or negligent driving and escapes from the scene without reporting to police or hospital shall be punished with imprisonment up to 10 years and fine. Stopping and helping is mandatory.',
      punishment: 'Imprisonment up to 10 years + Fine + License cancellation',
      keyPoints: [
        'Must stop immediately after accident',
        'Call ambulance: 102/108',
        'Inform police: 100',
        'Help injured to hospital',
        'Good Samaritan Law protects helpers',
      ],
    ),
    LawItem(
      id: '39',
      title: 'Pollution Norms & Vehicle Fitness',
      category: 'Traffic Rules',
      section: 'Section 190 MV Act',
      description: 'Emission standards and vehicle fitness',
      fullText: 'Every motor vehicle shall comply with emission standards. Vehicles older than 15 years (commercial) or 20 years (private) must obtain fitness certificate. Failure to comply attracts fine up to ₹10,000 and vehicle seizure.',
      punishment: 'Fine ₹10,000 + Vehicle seizure',
      keyPoints: [
        'PUC certificate mandatory every 6 months',
        'Fitness test for old vehicles',
        'Emission norms: BS-VI currently',
        'Modified silencers illegal',
        'Heavy smoke emission penalized',
      ],
    ),
    LawItem(
      id: '40',
      title: 'Parking Violations',
      category: 'Traffic Rules',
      section: 'Section 122 MV Act',
      description: 'Illegal parking and obstruction',
      fullText: 'Parking in no-parking zones, blocking traffic, parking on footpaths, or obstructing emergency routes is prohibited. Fine ranges from ₹500 to ₹2,000. Vehicle may be towed at owner\'s expense.',
      punishment: 'Fine ₹500-₹2,000 + Towing charges',
      keyPoints: [
        'Don\'t park on yellow lines',
        'Keep footpaths clear for pedestrians',
        'No parking near fire hydrants',
        'Don\'t block driveways or gates',
        'Use designated parking areas only',
      ],
    ),
  ];

  static List<String> get categories {
    final cats = allLaws.map((law) => law.category).toSet().toList();
    cats.sort();
    return cats;
  }

  static List<LawItem> getLawsByCategory(String category) {
    return allLaws.where((law) => law.category == category).toList();
  }

  static List<LawItem> searchLaws(String query) {
    final lowerQuery = query.toLowerCase();
    return allLaws.where((law) {
      return law.title.toLowerCase().contains(lowerQuery) ||
          law.description.toLowerCase().contains(lowerQuery) ||
          law.section.toLowerCase().contains(lowerQuery) ||
          law.keyPoints.any((point) => point.toLowerCase().contains(lowerQuery));
    }).toList();
  }
}
